FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip build-essential cmake git libglib2.0-dev pkg-config libzmq3-dev
# RUN apt-get install 

RUN python3 -m pip install pyzmq
